//! The served interface: one `async fn` per member of the contract.
//!
//! Every method has the same body — hand a copy of the engine to a blocking
//! thread and return the envelope it produces — so the file is long and
//! uninteresting on purpose. What matters is that the order below is the order
//! of [`tinydesktop_bus::names::METHODS`]; `test.rs` asserts the generated
//! dispatch table against that list, so a member added in one place and not the
//! other fails the build.
//!
//! The methods cannot be generated by a macro: `#[tinybus::interface]` reads
//! the `impl` block's items to build its dispatch table, and a `macro_rules!`
//! invocation inside that block is still unexpanded when it does. Writing them
//! out is what lets the macro see them.

use tinybus::{Error as TinyBusError, Result as TinyBusResult};
use tinydesktop_bus::{
    ClipboardGetRequest, ClipboardSetRequest, CloseAppRequest, DesktopResponse,
    DismissAllNotificationsRequest, DismissNotificationRequest, DragRequest, FindRequest,
    FocusWindowRequest, GetRequest, HoldKeyRequest, HoldMouseRequest, HoverRequest, IsRequest,
    LaunchRequest, ListAppsRequest, ListNotificationsRequest, ListSurfacesRequest,
    ListWindowsRequest, MouseClickRequest, MouseMoveRequest, MouseWheelRequest,
    MoveWindowRequest, NotificationActionRequest, PermissionsRequest, PressRequest, RefRequest,
    ResizeWindowRequest, ScreenshotRequest, ScrollRequest, SelectRequest, SetValueRequest,
    SnapshotRequest, TypeRequest, WaitRequest, WindowRequest,
};

use crate::{Desktop, Result};

/// The object served at [`tinydesktop_bus::names::OBJECT_PATH`].
///
/// It holds the configured engine and nothing else. Cloning it is cheap, which
/// is what lets every member hand a copy to a blocking thread instead of
/// borrowing one across an `await`.
#[derive(Debug, Clone)]
pub(crate) struct DesktopService {
    desktop: Desktop,
}

impl DesktopService {
    /// Builds the service from the module configuration blob.
    ///
    /// # Errors
    ///
    /// Propagates whatever [`Desktop::from_config`] rejects.
    pub(crate) fn from_config(config: &serde_json::Value) -> Result<Self> {
        Ok(Self {
            desktop: Desktop::from_config(config)?,
        })
    }

    /// Runs one engine command on a blocking thread.
    ///
    /// A panic inside a command surfaces as a `TinyBus` error rather than
    /// taking the runtime down: one malformed request must not cost every other
    /// caller their connection.
    async fn run<F>(&self, command: F) -> TinyBusResult<DesktopResponse>
    where
        F: FnOnce(Desktop) -> DesktopResponse + Send + 'static,
    {
        let desktop = self.desktop.clone();

        tokio::task::spawn_blocking(move || command(desktop))
            .await
            .map_err(|error| TinyBusError::failed(format!("desktop command failed: {error}")))
    }
}

#[tinybus::interface(name = "ai.tinyhumans.tinydesktop.Desktop")]
impl DesktopService {
    /// Walks an accessibility tree and allocates a ref per element.
    async fn snapshot(&self, request: SnapshotRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.snapshot(request)).await
    }

    /// Returns the elements matching a query.
    async fn find(&self, request: FindRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.find(request)).await
    }

    /// Reads one property of one ref.
    async fn get(&self, request: GetRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.get(request)).await
    }

    /// Tests one boolean state of one ref.
    async fn is(&self, request: IsRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.is(request)).await
    }

    /// Captures an application, window, or display as an image.
    async fn screenshot(&self, request: ScreenshotRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.screenshot(request)).await
    }

    /// Clicks a ref through its accessibility action.
    async fn click(&self, request: RefRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.click(request)).await
    }

    /// Double-clicks a ref.
    async fn double_click(&self, request: RefRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.double_click(request)).await
    }

    /// Triple-clicks a ref.
    async fn triple_click(&self, request: RefRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.triple_click(request)).await
    }

    /// Right-clicks a ref, opening its context menu.
    async fn right_click(&self, request: RefRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.right_click(request)).await
    }

    /// Types text into a ref.
    #[tinybus(name = "Type")]
    async fn type_text(&self, request: TypeRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.type_text(request)).await
    }

    /// Replaces a ref's value in one step.
    async fn set_value(&self, request: SetValueRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.set_value(request)).await
    }

    /// Empties a ref's value.
    async fn clear(&self, request: RefRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.clear(request)).await
    }

    /// Gives a ref keyboard focus.
    async fn focus(&self, request: RefRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.focus(request)).await
    }

    /// Selects an option within a ref.
    async fn select(&self, request: SelectRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.select(request)).await
    }

    /// Toggles a checkable ref.
    async fn toggle(&self, request: RefRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.toggle(request)).await
    }

    /// Checks a checkable ref.
    async fn check(&self, request: RefRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.check(request)).await
    }

    /// Unchecks a checkable ref.
    async fn uncheck(&self, request: RefRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.uncheck(request)).await
    }

    /// Expands an expandable ref.
    async fn expand(&self, request: RefRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.expand(request)).await
    }

    /// Collapses an expandable ref.
    async fn collapse(&self, request: RefRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.collapse(request)).await
    }

    /// Scrolls a scrollable ref.
    async fn scroll(&self, request: ScrollRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.scroll(request)).await
    }

    /// Scrolls a ref into view.
    async fn scroll_to(&self, request: RefRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.scroll_to(request)).await
    }

    /// Presses a key combination.
    async fn press(&self, request: PressRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.press(request)).await
    }

    /// Reserved for a stateful daemon; validates and then fails closed.
    async fn key_down(&self, request: HoldKeyRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.key_down(request)).await
    }

    /// Reserved for a stateful daemon; validates and then fails closed.
    async fn key_up(&self, request: HoldKeyRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.key_up(request)).await
    }

    /// Moves the cursor over a ref or a point.
    async fn hover(&self, request: HoverRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.hover(request)).await
    }

    /// Drags between two endpoints.
    async fn drag(&self, request: DragRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.drag(request)).await
    }

    /// Moves the cursor to a point.
    async fn mouse_move(&self, request: MouseMoveRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.mouse_move(request)).await
    }

    /// Clicks at a point.
    async fn mouse_click(&self, request: MouseClickRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.mouse_click(request)).await
    }

    /// Reserved for a stateful daemon; validates and then fails closed.
    async fn mouse_down(&self, request: HoldMouseRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.mouse_down(request)).await
    }

    /// Reserved for a stateful daemon; validates and then fails closed.
    async fn mouse_up(&self, request: HoldMouseRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.mouse_up(request)).await
    }

    /// Scrolls the wheel at a point.
    async fn mouse_wheel(&self, request: MouseWheelRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.mouse_wheel(request)).await
    }

    /// Starts an application, or attaches to a running one.
    async fn launch(&self, request: LaunchRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.launch(request)).await
    }

    /// Quits or terminates an application.
    async fn close_app(&self, request: CloseAppRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.close_app(request)).await
    }

    /// Lists running applications.
    async fn list_apps(&self, request: ListAppsRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.list_apps(request)).await
    }

    /// Lists windows.
    async fn list_windows(&self, request: ListWindowsRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.list_windows(request)).await
    }

    /// Lists displays.
    async fn list_displays(&self) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.list_displays()).await
    }

    /// Lists the surfaces an application currently exposes.
    async fn list_surfaces(&self, request: ListSurfacesRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.list_surfaces(request)).await
    }

    /// Brings a window forward.
    async fn focus_window(&self, request: FocusWindowRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.focus_window(request)).await
    }

    /// Resizes a window.
    async fn resize_window(&self, request: ResizeWindowRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.resize_window(request)).await
    }

    /// Moves a window's origin.
    async fn move_window(&self, request: MoveWindowRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.move_window(request)).await
    }

    /// Minimizes a window.
    async fn minimize(&self, request: WindowRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.minimize(request)).await
    }

    /// Maximizes a window.
    async fn maximize(&self, request: WindowRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.maximize(request)).await
    }

    /// Restores a minimized or maximized window.
    async fn restore(&self, request: WindowRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.restore(request)).await
    }

    /// Reads the pasteboard.
    async fn clipboard_get(&self, request: ClipboardGetRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.clipboard_get(request)).await
    }

    /// Writes the pasteboard.
    async fn clipboard_set(&self, request: ClipboardSetRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.clipboard_set(request)).await
    }

    /// Empties the pasteboard.
    async fn clipboard_clear(&self) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.clipboard_clear()).await
    }

    /// Lists notification-centre entries.
    async fn list_notifications(&self, request: ListNotificationsRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.list_notifications(request)).await
    }

    /// Invokes an action on a notification.
    async fn notification_action(&self, request: NotificationActionRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.notification_action(request)).await
    }

    /// Dismisses one notification.
    async fn dismiss_notification(&self, request: DismissNotificationRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.dismiss_notification(request)).await
    }

    /// Dismisses every notification, optionally scoped to one application.
    async fn dismiss_all_notifications(&self, request: DismissAllNotificationsRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.dismiss_all_notifications(request)).await
    }

    /// Blocks until a condition holds or the timeout expires.
    async fn wait(&self, request: WaitRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.wait(request)).await
    }

    /// Reports the engine version and target.
    async fn version(&self) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.version()).await
    }

    /// Reports permissions, the active session, and the latest snapshot.
    async fn status(&self) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.status()).await
    }

    /// Reports, and optionally prompts for, the permissions automation needs.
    async fn permissions(&self, request: PermissionsRequest) -> TinyBusResult<DesktopResponse> {
        self.run(move |desktop| desktop.permissions(request)).await
    }
}
